### ISSUE TITLE
It shows that I have successfully minted it, but the wallet does not have any realm

### ISSUE THREAD

**Issue by Wysten-Hgg** [disco-quotidie/realm-base#4]
You gave me the following prompt, and I found that the wallet only has one scan of the QR code for transfer transactions, and there is no transaction in the mint realm.

`Subrealm Minted Successfully! Wait for the transaction to be confirmed...`

**Comment by disco-quotidie** [comment]
Mint realm and mint subrealm, they all have transations.
It is not the case that you mint it elsewhere and transfer to you.
Atomicals are always minted during a taproot transaction.
That is what you have to wait for to be confirmed.

**Comment by Wysten-Hgg** [comment]
Thank you for your explanation. I need to learn more. Another thing is that I have successfully mint the realm.

**Comment by disco-quotidie** [comment]
Thank you for your feedback and care about this project.
Realm-base is planned to be published as open-source project. It aims to provide builders with a boilerplate application so that they can easily fork and customize any realm+subrealm+nft collection project. But it is not completed even for version 0 yet.
Development is delayed because of several problems and we are doing our best to carry on...

**Comment by Wysten-Hgg** [comment]
Thank you for your efforts and contributions to the atomicals protocol. I hope you can achieve success.
